<#
.SYNOPSIS
    Writes each stack's local configuration from the deployed resources.

.DESCRIPTION
    There is one connection: AI_ENDPOINT plus AI_KEY. -Mode chooses which endpoint
    gets written there:

      direct     the Azure AI Foundry resource, with its provider key
      apim       the classic APIM instance, with a revocable subscription key
      aigateway  the AI Gateway tier, with its runtime access key

    Nothing else changes between them - that is the point the demo makes. To show
    the contrast live, re-run with a different -Mode and restart the app.

    Nothing records which one you chose: the apps work it out from the endpoint and
    display it, so the page can never claim a mode it is not actually using.

    Two files are written, one per stack, and an existing copy of either is renamed
    to <name>.bak first:

      python\.env
      dotnet\AiGatewayDemo\appsettings.Development.json

    They go in the stack folders rather than the repo root because that is where
    each app actually looks. Python reads python\.env ahead of any root .env, and
    the .NET chain ranks appsettings.Development.json above every .env. A root file
    is therefore shadowed by whatever already sits in the stack folder - which made
    re-running this script look like it had done nothing at all. Both files are
    generated from one set of values, so they cannot drift apart.

    Secrets are written to disk. .gitignore excludes both files and the .bak copies -
    keep it that way, and prefer -UseUserSecrets on a shared machine, which stores
    the values outside the repo and leaves appsettings.Development.json alone.

.EXAMPLE
    .\03-set-local-env.ps1                    # through the gateway
    .\03-set-local-env.ps1 -Mode direct       # straight at the provider, to compare
    .\03-set-local-env.ps1 -Mode aigateway -AiGatewayEndpoint https://gw.azure-api.net/default/models -AiGatewayKey xxx
#>
[CmdletBinding()]
param(
    [ValidateSet('direct', 'apim', 'aigateway')]
    [string]$Mode = 'apim',
    # Overrides where the .env goes; the default is python\.env.
    [string]$Path,
    [switch]$UseUserSecrets,
    # AI Gateway tier (public preview) - registered by hand at ai.gateway.azure.com,
    # so its values are passed in rather than discovered.
    [string]$AiGatewayEndpoint = '',
    [string]$AiGatewayKey = '',
    [string]$AiGatewayChatModel = ''
)

. "$PSScriptRoot\00-common.ps1"

Assert-AzureCli | Out-Null
$state = Get-DemoState
$root = Get-RepoRoot

Write-Step 'Reading keys'
function Get-ResourceKey {
    param([Parameter(Mandatory)][string]$Name)
    (Invoke-Az @('cognitiveservices', 'account', 'keys', 'list',
        '--name', $Name, '-g', $state.ResourceGroup)).key1
}

$safetyKey = Get-ResourceKey -Name $state.ContentSafety
$docIntelKey = Get-ResourceKey -Name $state.DocIntelName

$gatewayUrl = if ($state.PSObject.Properties['GatewayUrl']) { $state.GatewayUrl } else { '' }
$subKey = if ($state.PSObject.Properties['SubscriptionKey']) { $state.SubscriptionKey } else { '' }

# ── resolve the one connection ────────────────────────────────────────
if ($Mode -eq 'apim' -and -not $gatewayUrl) {
    Write-Warn 'No gateway recorded yet - falling back to direct.'
    $Mode = 'direct'
}
if ($Mode -eq 'aigateway' -and -not $AiGatewayEndpoint) {
    Write-Warn 'No -AiGatewayEndpoint given - falling back to apim.'
    $Mode = if ($gatewayUrl) { 'apim' } else { 'direct' }
}

switch ($Mode) {
    'direct' {
        $aiEndpoint = $state.FoundryEndpoint
        $aiKey = Get-ResourceKey -Name $state.FoundryName
        $aiModel = $state.ChatModel
        # Straight at the resources, with their own keys.
        $safetyEndpoint = $state.SafetyEndpoint
        $docIntelEndpoint = $state.DocIntelEndpoint
    }
    'apim' {
        $aiEndpoint = "$gatewayUrl/$($state.AoaiApiPath)"
        $aiKey = $subKey
        $aiModel = $state.ChatModel
        # The same gateway fronts the other two services, on its own paths and
        # with the same subscription key.
        $safetyEndpoint = "$gatewayUrl/$($state.SafetyApiPath)"
        $docIntelEndpoint = "$gatewayUrl/$($state.DocIntelApiPath)"
        $safetyKey = $subKey
        $docIntelKey = $subKey
    }
    'aigateway' {
        $aiEndpoint = $AiGatewayEndpoint
        $aiKey = $AiGatewayKey
        # Routing there is by the model asset name in the request body, not by path.
        $aiModel = if ($AiGatewayChatModel) { $AiGatewayChatModel } else { $state.ChatModel }
        $safetyEndpoint = $state.SafetyEndpoint
        $docIntelEndpoint = $state.DocIntelEndpoint
    }
}

# ── compose ───────────────────────────────────────────────────────────
$lines = @(
    "# Generated by 03-set-local-env.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
    "# Resource group: $($state.ResourceGroup)"
    '# Contains secrets - never commit this file.'
    '#'
    '# One connection. Re-run 03-set-local-env.ps1 with a different -Mode to point'
    '# it somewhere else; no application code changes either way. The apps derive'
    '# how they are connected from this endpoint - nothing here declares it.'
    ''
    "AI_ENDPOINT=$aiEndpoint"
    "AI_KEY=$aiKey"
    'AI_KEY_HEADER=api-key'
    "AI_CHAT_MODEL=$aiModel"
    "AI_EMBEDDING_MODEL=$($state.EmbeddingModel)"
    ''
    '# Content Safety: guardrails for text and image.'
    "CONTENT_SAFETY_ENDPOINT=$safetyEndpoint"
    "CONTENT_SAFETY_KEY=$safetyKey"
    'CONTENT_SAFETY_THRESHOLD=4'
    'CONTENT_SAFETY_CHECK_COMPLETION=true'
    ''
    '# Document Intelligence: upload -> extract -> chunk -> embed -> index.'
    "DOC_INTEL_ENDPOINT=$docIntelEndpoint"
    "DOC_INTEL_KEY=$docIntelKey"
    ''
    'RAG_TOP_K=4'
    'RAG_CHUNK_CHARS=1200'
    'RAG_CHUNK_OVERLAP=150'
    'MAX_UPLOAD_MB=20'
)

function ConvertTo-SettingMap {
    <#  Reads the block above back into key/value pairs. The .env file, the JSON and
        user-secrets are all generated from this one map, so a setting added above
        reaches every stack and the two files cannot drift apart.  #>
    # AllowEmptyString: the composed block uses blank lines as spacers, and a
    # Mandatory [string[]] rejects an empty element without it.
    param([Parameter(Mandatory)][AllowEmptyString()][string[]]$Lines)

    $map = [ordered]@{}
    foreach ($line in $Lines) {
        if ($line -match '^\s*#' -or $line -notmatch '=') { continue }
        $key, $value = $line -split '=', 2
        if ($value) { $map[$key.Trim()] = $value.Trim() }
    }
    $map
}

function Backup-Existing {
    <#  Renames a file to <name>.bak before it is replaced, so a hand-edited config is
        never lost to a re-run. Any older .bak is overwritten - one step back, not a
        history. These copies hold real keys; .gitignore covers *.bak for that reason.  #>
    param([Parameter(Mandatory)][string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) { return $false }
    Move-Item -LiteralPath $Path -Destination "$Path.bak" -Force
    Write-Note "Kept the previous file as $(Split-Path -Leaf $Path).bak"
    $true
}

function Get-Kept {
    <#  Returns an existing JSON property if it is there, otherwise the default.
        StrictMode makes a missing property terminating, hence the explicit test.  #>
    param($Object, [Parameter(Mandatory)][string]$Name, $Default)

    if ($Object -and $Object.PSObject.Properties[$Name]) { return $Object.$Name }
    $Default
}

$settings = ConvertTo-SettingMap -Lines $lines

# ───────────────────────── the Python app: python\.env ─────────────────────────
if (-not $Path) { $Path = Get-EnvFilePath }

Write-Step "Writing $Path"
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Path) | Out-Null
Backup-Existing -Path $Path | Out-Null
Set-Utf8NoBom -Path $Path -Content ($lines -join [Environment]::NewLine)
Write-Ok "$($settings.Count) settings written."

# Nothing writes a repo-root .env any more. Leaving one there would be a second,
# stale copy of the keys that no app reads, because Python takes the stack-local
# file first - so retire it rather than let it sit and mislead.
$rootEnv = Join-Path $root '.env'
if ((Test-Path -LiteralPath $rootEnv) -and
    ((Resolve-Path -LiteralPath $rootEnv).Path -ne (Resolve-Path -LiteralPath $Path).Path)) {
    Write-Step 'Retiring the repo-root .env'
    Write-Note 'Each stack now has its own file; this one is shadowed by both.'
    Backup-Existing -Path $rootEnv | Out-Null
}

# ───────────────────────── the Razor app ─────────────────────────
$project = Join-Path $root 'dotnet' | Join-Path -ChildPath 'AiGatewayDemo'
$appSettings = Join-Path $project 'appsettings.Development.json'

if ($UseUserSecrets) {
    Write-Step 'Storing the values in dotnet user-secrets'
    Write-Note 'appsettings.Development.json is left alone - user-secrets outrank it.'

    & dotnet user-secrets init --project $project | Out-Null
    $settings | ConvertTo-Json -Depth 3 | & dotnet user-secrets set --project $project 2>&1 | Out-Null
    Write-Ok "$($settings.Count) secrets stored for the Razor app."
}
else {
    Write-Step "Writing $appSettings"

    # Read before the backup renames it away. Local diagnostics are the developer's,
    # not this script's: keep whatever logging is already configured and replace only
    # the connection keys.
    $existing = $null
    if (Test-Path -LiteralPath $appSettings) {
        try { $existing = Get-Content -LiteralPath $appSettings -Raw | ConvertFrom-Json }
        catch { Write-Warn "Could not parse the existing file, so the defaults are used. $($_.Exception.Message)" }
    }

    $defaultLogging = [ordered]@{
        LogLevel = [ordered]@{
            'Default'                    = 'Information'
            'Microsoft.AspNetCore'       = 'Information'
            'Microsoft.Hosting.Lifetime' = 'Information'
            'AiGatewayDemo'              = 'Debug'
            'System.Net.Http.HttpClient' = 'Information'
        }
    }

    $document = [ordered]@{
        '_comment'       = "Generated by 03-set-local-env.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm') from resource group $($state.ResourceGroup). Re-running the script replaces this file and keeps the previous one as .bak. It holds real keys - git-ignored, never commit it."
        '_precedence'    = 'Lowest to highest: appsettings.json -> appsettings.Development.json -> user-secrets -> environment variables. A .env only fills keys still empty after all of those, which is why this file - not a repo-root .env - is what the Razor app actually reads. Whatever wins, the page Connection panel names it.'
        '_logging'       = 'System.Net.Http.HttpClient at Information logs every outbound call the app makes, which is worth having during the demo. Every key under Logging:LogLevel must be a real log level - a comment key there fails startup, so these notes stay at the top level.'
        'DetailedErrors' = Get-Kept -Object $existing -Name 'DetailedErrors' -Default $true
        'Logging'        = Get-Kept -Object $existing -Name 'Logging' -Default $defaultLogging
    }
    foreach ($key in $settings.Keys) { $document[$key] = $settings[$key] }

    Backup-Existing -Path $appSettings | Out-Null
    Set-Utf8NoBom -Path $appSettings -Content ($document | ConvertTo-Json -Depth 6)
    Write-Ok "$($settings.Count) settings written; logging configuration preserved."
}

Write-Step 'Done'
Write-Host "  Wrote the $Mode endpoint. The apps derive and display that themselves."
Write-Host "  Endpoint  $aiEndpoint"
Write-Host "  Model     $aiModel"
Write-Host "  Python    $Path"
Write-Host "  .NET      $(if ($UseUserSecrets) { 'dotnet user-secrets' } else { $appSettings })"
Write-Host ''
Write-Host '  Next: .\04-test-gateway.ps1   then   dotnet\start.cmd  or  python\start.cmd' -ForegroundColor Cyan
