<#
.SYNOPSIS
    Writes the .env file that both apps read, from the deployed resources.

.DESCRIPTION
    There is one connection: AI_ENDPOINT plus AI_KEY. -Mode chooses which endpoint
    gets written there:

      direct     the Azure OpenAI resource, with its provider key
      apim       the classic APIM instance, with a revocable subscription key
      aigateway  the AI Gateway tier, with its runtime access key

    Nothing else changes between them - that is the point the demo makes. To show
    the contrast live, re-run with a different -Mode and restart the app.

    Nothing records which one you chose: the apps work it out from the endpoint and
    display it, so the page can never claim a mode it is not actually using.

    Secrets are written to disk. The repo's .gitignore excludes .env - keep it that
    way, and prefer -UseUserSecrets for the .NET app on a shared machine.

.EXAMPLE
    .\03-set-local-env.ps1                    # through the gateway
    .\03-set-local-env.ps1 -Mode direct       # straight at the provider, to compare
    .\03-set-local-env.ps1 -Mode aigateway -AiGatewayEndpoint https://gw.azure-api.net/default/models -AiGatewayKey xxx
#>
[CmdletBinding()]
param(
    [ValidateSet('direct', 'apim', 'aigateway')]
    [string]$Mode = 'apim',
    [string]$Path,
    [switch]$UseUserSecrets,
    # AI Gateway tier (public preview) - registered by hand at ai.gateway.azure.com,
    # so its values are passed in rather than discovered.
    [string]$AiGatewayEndpoint = '',
    [string]$AiGatewayKey = '',
    [string]$AiGatewayChatModel = ''
)

. "$PSScriptRoot\00-common.ps1"

Assert-AzureCli | Out-Null
$state = Get-DemoState
$root = Get-RepoRoot

if (-not $Path) { $Path = Join-Path $root '.env' }

Write-Step 'Reading keys'
function Get-ResourceKey {
    param([Parameter(Mandatory)][string]$Name)
    (Invoke-Az @('cognitiveservices', 'account', 'keys', 'list',
        '--name', $Name, '-g', $state.ResourceGroup)).key1
}

$safetyKey = Get-ResourceKey -Name $state.ContentSafety
$docIntelKey = Get-ResourceKey -Name $state.DocIntelName

$gatewayUrl = if ($state.PSObject.Properties['GatewayUrl']) { $state.GatewayUrl } else { '' }
$subKey = if ($state.PSObject.Properties['SubscriptionKey']) { $state.SubscriptionKey } else { '' }

# ── resolve the one connection ────────────────────────────────────────
if ($Mode -eq 'apim' -and -not $gatewayUrl) {
    Write-Warn 'No gateway recorded yet - falling back to direct.'
    $Mode = 'direct'
}
if ($Mode -eq 'aigateway' -and -not $AiGatewayEndpoint) {
    Write-Warn 'No -AiGatewayEndpoint given - falling back to apim.'
    $Mode = if ($gatewayUrl) { 'apim' } else { 'direct' }
}

switch ($Mode) {
    'direct' {
        $aiEndpoint = $state.OpenAiEndpoint
        $aiKey = Get-ResourceKey -Name $state.OpenAiName
        $aiModel = $state.ChatModel
        # Straight at the resources, with their own keys.
        $safetyEndpoint = $state.SafetyEndpoint
        $docIntelEndpoint = $state.DocIntelEndpoint
    }
    'apim' {
        $aiEndpoint = "$gatewayUrl/$($state.AoaiApiPath)"
        $aiKey = $subKey
        $aiModel = $state.ChatModel
        # The same gateway fronts the other two services, on its own paths and
        # with the same subscription key.
        $safetyEndpoint = "$gatewayUrl/$($state.SafetyApiPath)"
        $docIntelEndpoint = "$gatewayUrl/$($state.DocIntelApiPath)"
        $safetyKey = $subKey
        $docIntelKey = $subKey
    }
    'aigateway' {
        $aiEndpoint = $AiGatewayEndpoint
        $aiKey = $AiGatewayKey
        # Routing there is by the model asset name in the request body, not by path.
        $aiModel = if ($AiGatewayChatModel) { $AiGatewayChatModel } else { $state.ChatModel }
        $safetyEndpoint = $state.SafetyEndpoint
        $docIntelEndpoint = $state.DocIntelEndpoint
    }
}

# ── compose ───────────────────────────────────────────────────────────
$lines = @(
    "# Generated by 03-set-local-env.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
    "# Resource group: $($state.ResourceGroup)"
    '# Contains secrets - never commit this file.'
    '#'
    '# One connection. Re-run 03-set-local-env.ps1 with a different -Mode to point'
    '# it somewhere else; no application code changes either way. The apps derive'
    '# how they are connected from this endpoint - nothing here declares it.'
    ''
    "AI_ENDPOINT=$aiEndpoint"
    "AI_KEY=$aiKey"
    'AI_KEY_HEADER=api-key'
    "AI_CHAT_MODEL=$aiModel"
    "AI_EMBEDDING_MODEL=$($state.EmbeddingModel)"
    ''
    '# Content Safety: guardrails for text and image.'
    "CONTENT_SAFETY_ENDPOINT=$safetyEndpoint"
    "CONTENT_SAFETY_KEY=$safetyKey"
    'CONTENT_SAFETY_THRESHOLD=4'
    'CONTENT_SAFETY_CHECK_COMPLETION=true'
    ''
    '# Document Intelligence: upload -> extract -> chunk -> embed -> index.'
    "DOC_INTEL_ENDPOINT=$docIntelEndpoint"
    "DOC_INTEL_KEY=$docIntelKey"
    ''
    'RAG_TOP_K=4'
    'RAG_CHUNK_CHARS=1200'
    'RAG_CHUNK_OVERLAP=150'
    'MAX_UPLOAD_MB=20'
)

Write-Step "Writing $Path"
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Path) | Out-Null
$lines -join [Environment]::NewLine | Set-Content -Path $Path -Encoding utf8
Write-Ok "$($lines.Count) lines written."

# ── optional: .NET user-secrets ───────────────────────────────────────
if ($UseUserSecrets) {
    Write-Step 'Storing the same values in dotnet user-secrets'
    $project = Join-Path $root 'dotnet\AiGatewayDemo'

    $secrets = [ordered]@{}
    foreach ($line in $lines) {
        if ($line -match '^\s*#' -or $line -notmatch '=') { continue }
        $key, $value = $line -split '=', 2
        if ($value) { $secrets[$key.Trim()] = $value.Trim() }
    }

    & dotnet user-secrets init --project $project | Out-Null
    $secrets | ConvertTo-Json -Depth 3 | & dotnet user-secrets set --project $project 2>&1 | Out-Null
    Write-Ok "$($secrets.Count) secrets stored for the Razor app."
}

Write-Step 'Done'
Write-Host "  Wrote the $Mode endpoint. The apps derive and display that themselves."
Write-Host "  Endpoint  $aiEndpoint"
Write-Host "  Model     $aiModel"
Write-Host ''
Write-Host '  Next: .\04-test-gateway.ps1   then   .\05-run-dotnet.ps1  or  .\06-run-python.ps1' -ForegroundColor Cyan
